OMP_NUM_THREADS=1 python -m torch.distributed.launch --nproc_per_node=8 main_finetune.py \
    --accum_iter 2 \
    --batch_size 64 \
    --model vit_base_patch16 \
    --finetune /home/aiscuser/mae_p2p_3_11/mae/p2p_vitb_09/checkpoint-299.pth \
    --epochs 100 \
    --blr 5e-4 --layer_decay 0.65 \
    --weight_decay 0.05 --drop_path 0.1 --mixup 0.8 --cutmix 1.0 --reprob 0.25 \
    --dist_eval --data_path /home/dataset/ImageNet \
    --output_dir ./p2p_vitb_09_ft\
    --log_dir ./p2p_vitb_09_ft \